### ISSUE TITLE
Not logging exceptions

### ISSUE THREAD

**Issue by nemanjam** [stevebauman/log-reader#7]
When I used Laravel's default file handler all exceptions were logged. I installed package and set default eloquent handler and now only few exceptions are logged and I can't spot logic which one and by which criteria they suddenly got missed out. I'd like all exceptions logged, where should I look?

**Comment by nemanjam** [comment]
You can close this, phpunit was intercepting exceptions I expected to see in the log.

**Comment by stevebauman** [comment]
Ok thanks for following up! Glad you have the issue resolved.
